services:
  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: epermitted
      POSTGRES_PASSWORD: supersecret
      POSTGRES_DB: epermitted_dev
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data:
